In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [5]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [6]:
print(reg.coef_)
print(reg.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [7]:
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [8]:
from sklearn.linear_model import SGDRegressor

In [11]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [12]:
import random
batch_size = 35

for i in range(100):  # we are doing 100 iteration by randomly selecting 35 rows at a time
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])   # we are training batch by batch using incremental learning(online learning)

In [16]:
idx = random.sample(range(X_train.shape[0]),batch_size)
X_train[idx]

array([[ 5.38306037e-03, -4.46416365e-02, -3.63846922e-02,
         2.18723855e-02,  3.93485161e-03,  1.55961395e-02,
         8.14208361e-03, -2.59226200e-03, -3.19876395e-02,
        -4.66408736e-02],
       [ 7.44012909e-02, -4.46416365e-02,  3.15174685e-02,
         1.01057958e-01,  4.65893902e-02,  3.68902349e-02,
         1.55053592e-02, -2.59226200e-03,  3.36538149e-02,
         4.44854786e-02],
       [-9.14709343e-03,  5.06801187e-02, -3.96181284e-02,
        -4.00989321e-02, -8.44872411e-03,  1.62224364e-02,
        -6.54906725e-02,  7.12099798e-02,  1.77653196e-02,
        -6.73514081e-02],
       [-5.51455498e-03,  5.06801187e-02, -8.36157828e-03,
        -2.22757132e-03, -3.32158756e-02, -6.36304213e-02,
        -3.60375700e-02, -2.59226200e-03,  8.05900527e-02,
         7.20651633e-03],
       [ 2.35457526e-02, -4.46416365e-02, -3.63846922e-02,
         7.91388369e-05,  1.18294590e-03,  3.46981957e-02,
        -4.34008457e-02,  3.43088589e-02, -3.32455926e-02,
         6.

In [17]:
sgd.coef_

array([  50.03598036,  -66.35085315,  356.52366377,  235.64262438,
         42.38033988,   -3.81321975, -172.74991088,  145.75097043,
        326.03568372,  128.10362041])

In [18]:
sgd.intercept_

array([163.70614084])

In [19]:
y_pred = sgd.predict(X_test)

In [20]:
r2_score(y_test,y_pred)

0.40391512340125757

In [21]:
# lets make batch size = no of rows --- batch gradient descent

batch_size = 100

for i in range(1):  # we are doing 1 iteration by  selecting all rows at a time
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx]) 

In [23]:
print(sgd.intercept_)
print(sgd.coef_)
y_pred = sgd.predict(X_test)
r2_score(y_test,y_pred)

[150.27638657]
[  47.78353761  -71.70600341  360.89225533  236.29433964   38.2911032
   -8.93464711 -170.83980975  141.30593071  327.55743307  123.73765543]


0.4319287812002305

In [24]:
# lets make batch size as 1 p-- stochastic gradient descent

batch_size = 1

for i in range(1):  # we are doing 1 iteration by  selecting all rows at a time
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx]) 

In [25]:
print(sgd.intercept_)
print(sgd.coef_)
y_pred = sgd.predict(X_test)
r2_score(y_test,y_pred)

[153.84086517]
[  47.89288432  -71.52463815  360.85884174  236.30858051   38.34398242
   -8.83654964 -170.80907907  141.2755476   327.44891118  123.93927895]


0.43166919512782986

In [30]:
# comparing this with inbuild stochastic

sgd = SGDRegressor(learning_rate='constant')
sgd.fit(X_train,y_train) 
print(sgd.intercept_)
print(sgd.coef_)
y_pred = sgd.predict(X_test)
r2_score(y_test,y_pred)

[152.84073465]
[  53.83967114  -72.07323707  357.77302031  252.30256046   14.6043688
  -33.19577596 -174.94941076  128.2305855   324.87365528  128.04382954]


0.4360187098156272

In [ ]:
# we are getting different becasue sgd alw